[logger]
level = "INFO"
disable_sampling = false
timestamp_field_name = "ts"
level_field_name = "level"
message_field_name = "msg"
error_field_name = "error"
#time_field_format = 2006-01-02T15:04:05Z07:00

[database]
db_type = "in-memory"

[grpc]
host = "0.0.0.0"
port = "8090"

[http]
host = "0.0.0.0"
port = "8080"

[amqp]
url = "amqp://guest:guest@localhost:5672/"
queue = "events"

[scheduler]
db_read_interval = "30s"